[book]
authors = ["Anthony Dodd", "Attila Bagossy"]
language = "en"
multilingual = false
src = "guide/src"
title = "The Agreed Guide"
description = "User guide for the Agreed library."

[build]
build-dir = "guide/book"
create-missing = false
